version: "3.3"
services:
 #Plantilla del servicio "db"
  bd:
 #Se basa en la imagen "mysql", version 5.7
   image: mysql:5.7
 #Damos persistencia en el volumen "db_data" el directorio
 #"/var/lib/mysql
   volumes:
    - bd_data:/var/lib/mysql
 #Indica que siempre que el servicio finalice, se reiniciará
   restart: always
 #Define un conjunto de variables de entorno para estos contenedores,
   environment:
     MYSQL_ROOT_PASSWORD: daw2
     MYSQL_DATABASE: daw2
     MYSQL_USER: daw2
     MYSQL_PASSWORD: daw2
#Plantilla del servicio "wordpress"
  wordpress:
    depends_on:
      - bd
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    volumes:
    - ./datos:/var/www/html
 #Definimos variables de entorno.
    environment:
      WORDPRESS_DB_HOST: bd:3306
      WORDPRESS_DB_USER: daw2
      WORDPRESS_DB_PASSWORD: daw2
      WORDPRESS_DB_NAME: daw2
#Creamos el volumen para Mysql
volumes:
   bd_data:
